create database h1b_data;

use h1b_data;

CREATE TABLE h1b_data (
CASE_NUMBER VARCHAR(50),
CASE_STATUS VARCHAR(50),
RECEIVED_DATE VARCHAR(50),
DECISION_DATE VARCHAR(50),
ORIGINAL_CERT_DATE VARCHAR(50),
VISA_CLASS VARCHAR(50),
JOB_TITLE VARCHAR(100),
SOC_CODE VARCHAR(50),
SOC_TITLE VARCHAR(100),
FULL_TIME_POSITION VARCHAR(100),
BEGIN_DATE VARCHAR(50),
END_DATE VARCHAR(50),
TOTAL_WORKER_POSITIONS VARCHAR(50),
NEW_EMPLOYMENT VARCHAR(50),
CONTINUED_EMPLOYMENT VARCHAR(50),
CHANGE_PREVIOUS_EMPLOYMENT VARCHAR(50),
NEW_CONCURRENT_EMPLOYMENT VARCHAR(50),
CHANGE_EMPLOYER VARCHAR(50),
AMENDED_PETITION VARCHAR(50),
EMPLOYER_NAME VARCHAR(200),
TRADE_NAME_DBA VARCHAR(200),
EMPLOYER_ADDRESS1 VARCHAR(100),
EMPLOYER_ADDRESS2 VARCHAR(100),
EMPLOYER_CITY VARCHAR(100),
EMPLOYER_STATE VARCHAR(50),
EMPLOYER_POSTAL_CODE VARCHAR(50),
EMPLOYER_COUNTRY VARCHAR(50),
EMPLOYER_PROVINCE VARCHAR(50),
EMPLOYER_PHONE VARCHAR(20),
EMPLOYER_PHONE_EXT VARCHAR(50),
EMPLOYER_FEIN VARCHAR(50),
NAICS_CODE VARCHAR(50),
EMPLOYER_POC_LAST_NAME VARCHAR(100),
EMPLOYER_POC_FIRST_NAME VARCHAR(100),
EMPLOYER_POC_MIDDLE_NAME VARCHAR(100),
EMPLOYER_POC_JOB_TITLE VARCHAR(100),
EMPLOYER_POC_ADDRESS1 VARCHAR(200),
EMPLOYER_POC_ADDRESS2 VARCHAR(200),
EMPLOYER_POC_CITY VARCHAR(100),
EMPLOYER_POC_STATE VARCHAR(50),
EMPLOYER_POC_POSTAL_CODE VARCHAR(50),
EMPLOYER_POC_COUNTRY VARCHAR(50),
EMPLOYER_POC_PROVINCE VARCHAR(50),
EMPLOYER_POC_PHONE VARCHAR(50),
EMPLOYER_POC_PHONE_EXT VARCHAR(50),
EMPLOYER_POC_EMAIL VARCHAR(200),
AGENT_REPRESENTING_EMPLOYER VARCHAR(100),
AGENT_ATTORNEY_LAST_NAME VARCHAR(100),
AGENT_ATTORNEY_FIRST_NAME VARCHAR(100),
AGENT_ATTORNEY_MIDDLE_NAME VARCHAR(100),
AGENT_ATTORNEY_ADDRESS1 VARCHAR(200),
AGENT_ATTORNEY_ADDRESS2 VARCHAR(200),
AGENT_ATTORNEY_CITY VARCHAR(100),
AGENT_ATTORNEY_STATE VARCHAR(100),
AGENT_ATTORNEY_POSTAL_CODE VARCHAR(50),
AGENT_ATTORNEY_COUNTRY VARCHAR(50),
AGENT_ATTORNEY_PROVINCE VARCHAR(50),
AGENT_ATTORNEY_PHONE VARCHAR(50),
AGENT_ATTORNEY_PHONE_EXT VARCHAR(50),
AGENT_ATTORNEY_EMAIL_ADDRESS VARCHAR(200),
LAWFIRM_NAME_BUSINESS_NAME VARCHAR(200),
STATE_OF_HIGHEST_COURT VARCHAR(100),
NAME_OF_HIGHEST_STATE_COURT VARCHAR(200),
WORKSITE_WORKERS VARCHAR(50),
SECONDARY_ENTITY VARCHAR(50),
SECONDARY_ENTITY_BUSINESS_NAME VARCHAR(200),
WORKSITE_ADDRESS1 VARCHAR(200),
WORKSITE_ADDRESS2 VARCHAR(200),
WORKSITE_CITY VARCHAR(100),
WORKSITE_COUNTY VARCHAR(100),
WORKSITE_STATE VARCHAR(50),
WORKSITE_POSTAL_CODE VARCHAR(20),
WAGE_RATE_OF_PAY_FROM VARCHAR(50),
WAGE_RATE_OF_PAY_TO VARCHAR(50),
WAGE_UNIT_OF_PAY VARCHAR(50),
PREVAILING_WAGE VARCHAR(50),
PW_UNIT_OF_PAY VARCHAR(50),
PW_TRACKING_NUMBER VARCHAR(100),
PW_WAGE_LEVEL VARCHAR(50),
PW_OES_YEAR VARCHAR(50),
PW_OTHER_SOURCE VARCHAR(200),
PW_OTHER_YEAR VARCHAR(50),
PW_SURVEY_PUBLISHER VARCHAR(200),
PW_SURVEY_NAME VARCHAR(200),
TOTAL_WORKSITE_LOCATIONS VARCHAR(10),
AGREE_TO_LC_STATEMENT VARCHAR(50),
`H-1B_DEPENDENT` VARCHAR(50),
WILLFUL_VIOLATOR VARCHAR(50),
SUPPORT_H1B VARCHAR(50),
STATUTORY_BASIS VARCHAR(100),
APPENDIX_A_ATTACHED VARCHAR(50),
PUBLIC_DISCLOSURE VARCHAR(100),
PREPARER_LAST_NAME VARCHAR(100),
PREPARER_FIRST_NAME VARCHAR(100),
PREPARER_MIDDLE_INITIAL VARCHAR(50),
PREPARER_BUSINESS_NAME VARCHAR(200),
PREPARER_EMAIL VARCHAR(100)
);

select * from h1b_data;

select count(*) from h1b_data;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/LCA_Disclosure_Data_FY2025_Q1.csv'
INTO TABLE h1b_data
CHARACTER SET latin1
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;


select * from h1b_data;


select count(*) from h1b_data;


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/LCA_Disclosure_Data_FY2025_Q2.csv'
INTO TABLE h1b_data
CHARACTER SET latin1
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(
@CASE_NUMBER,
@CASE_STATUS,
@RECEIVED_DATE,
@DECISION_DATE,
@ORIGINAL_CERT_DATE,
@VISA_CLASS,
@JOB_TITLE,
@SOC_CODE,
@SOC_TITLE,
@FULL_TIME_POSITION,
@BEGIN_DATE,
@END_DATE,
@TOTAL_WORKER_POSITIONS,
@NEW_EMPLOYMENT,
@CONTINUED_EMPLOYMENT,
@CHANGE_PREVIOUS_EMPLOYMENT,
@NEW_CONCURRENT_EMPLOYMENT,
@CHANGE_EMPLOYER,
@AMENDED_PETITION,
@EMPLOYER_NAME,
@TRADE_NAME_DBA,
@EMPLOYER_ADDRESS1,
@EMPLOYER_ADDRESS2,
@EMPLOYER_CITY,
@EMPLOYER_STATE,
@EMPLOYER_POSTAL_CODE,
@EMPLOYER_COUNTRY,
@EMPLOYER_PROVINCE,
@EMPLOYER_PHONE,
@EMPLOYER_PHONE_EXT,
@EMPLOYER_FEIN,
@NAICS_CODE,
@EMPLOYER_POC_LAST_NAME,
@EMPLOYER_POC_FIRST_NAME,
@EMPLOYER_POC_MIDDLE_NAME,
@EMPLOYER_POC_JOB_TITLE,
@EMPLOYER_POC_ADDRESS1,
@EMPLOYER_POC_ADDRESS2,
@EMPLOYER_POC_CITY,
@EMPLOYER_POC_STATE,
@EMPLOYER_POC_POSTAL_CODE,
@EMPLOYER_POC_COUNTRY,
@EMPLOYER_POC_PROVINCE,
@EMPLOYER_POC_PHONE,
@EMPLOYER_POC_PHONE_EXT,
@EMPLOYER_POC_EMAIL,
@AGENT_REPRESENTING_EMPLOYER,
@AGENT_ATTORNEY_LAST_NAME,
@AGENT_ATTORNEY_FIRST_NAME,
@AGENT_ATTORNEY_MIDDLE_NAME,
@AGENT_ATTORNEY_ADDRESS1,
@AGENT_ATTORNEY_ADDRESS2,
@AGENT_ATTORNEY_CITY,
@AGENT_ATTORNEY_STATE,
@AGENT_ATTORNEY_POSTAL_CODE,
@AGENT_ATTORNEY_COUNTRY,
@AGENT_ATTORNEY_PROVINCE,
@AGENT_ATTORNEY_PHONE,
@AGENT_ATTORNEY_PHONE_EXT,
@AGENT_ATTORNEY_EMAIL_ADDRESS,
@LAWFIRM_NAME_BUSINESS_NAME,
@STATE_OF_HIGHEST_COURT,
@NAME_OF_HIGHEST_STATE_COURT,
@WORKSITE_WORKERS,
@SECONDARY_ENTITY,
@SECONDARY_ENTITY_BUSINESS_NAME,
@WORKSITE_ADDRESS1,
@WORKSITE_ADDRESS2,
@WORKSITE_CITY,
@WORKSITE_COUNTY,
@WORKSITE_STATE,
@WORKSITE_POSTAL_CODE,
@WAGE_RATE_OF_PAY_FROM,
@WAGE_RATE_OF_PAY_TO,
@WAGE_UNIT_OF_PAY,
@PREVAILING_WAGE,
@PW_UNIT_OF_PAY,
@PW_TRACKING_NUMBER,
@PW_WAGE_LEVEL,
@PW_OES_YEAR,
@PW_OTHER_SOURCE,
@PW_OTHER_YEAR,
@PW_SURVEY_PUBLISHER,
@PW_SURVEY_NAME,
@TOTAL_WORKSITE_LOCATIONS,
@AGREE_TO_LC_STATEMENT,
@H1B_DEPENDENT,
@WILLFUL_VIOLATOR,
@SUPPORT_H1B,
@STATUTORY_BASIS,
@APPENDIX_A_ATTACHED,
@PUBLIC_DISCLOSURE,
@PREPARER_LAST_NAME,
@PREPARER_FIRST_NAME,
@PREPARER_MIDDLE_INITIAL,
@PREPARER_BUSINESS_NAME,
@PREPARER_EMAIL
)
SET
CASE_NUMBER=@CASE_NUMBER,
CASE_STATUS=@CASE_STATUS,
RECEIVED_DATE=@RECEIVED_DATE,
DECISION_DATE=@DECISION_DATE,
ORIGINAL_CERT_DATE=@ORIGINAL_CERT_DATE,
VISA_CLASS=@VISA_CLASS,
JOB_TITLE=@JOB_TITLE,
SOC_CODE=@SOC_CODE,
SOC_TITLE=@SOC_TITLE,
FULL_TIME_POSITION=@FULL_TIME_POSITION,
BEGIN_DATE=@BEGIN_DATE,
END_DATE=@END_DATE,
TOTAL_WORKER_POSITIONS=@TOTAL_WORKER_POSITIONS,
NEW_EMPLOYMENT=@NEW_EMPLOYMENT,
CONTINUED_EMPLOYMENT=@CONTINUED_EMPLOYMENT,
CHANGE_PREVIOUS_EMPLOYMENT=@CHANGE_PREVIOUS_EMPLOYMENT,
NEW_CONCURRENT_EMPLOYMENT=@NEW_CONCURRENT_EMPLOYMENT,
CHANGE_EMPLOYER=@CHANGE_EMPLOYER,
AMENDED_PETITION=@AMENDED_PETITION,
EMPLOYER_NAME=@EMPLOYER_NAME,
TRADE_NAME_DBA=@TRADE_NAME_DBA,
EMPLOYER_ADDRESS1=@EMPLOYER_ADDRESS1,
EMPLOYER_ADDRESS2=@EMPLOYER_ADDRESS2,
EMPLOYER_CITY=@EMPLOYER_CITY,
EMPLOYER_STATE=@EMPLOYER_STATE,
EMPLOYER_POSTAL_CODE=@EMPLOYER_POSTAL_CODE,
EMPLOYER_COUNTRY=@EMPLOYER_COUNTRY,
EMPLOYER_PROVINCE=@EMPLOYER_PROVINCE,
EMPLOYER_PHONE=@EMPLOYER_PHONE,
EMPLOYER_PHONE_EXT=@EMPLOYER_PHONE_EXT,
EMPLOYER_FEIN=@EMPLOYER_FEIN,
NAICS_CODE=@NAICS_CODE,
EMPLOYER_POC_LAST_NAME=@EMPLOYER_POC_LAST_NAME,
EMPLOYER_POC_FIRST_NAME=@EMPLOYER_POC_FIRST_NAME,
EMPLOYER_POC_MIDDLE_NAME=@EMPLOYER_POC_MIDDLE_NAME,
EMPLOYER_POC_JOB_TITLE=@EMPLOYER_POC_JOB_TITLE,
EMPLOYER_POC_ADDRESS1=@EMPLOYER_POC_ADDRESS1,
EMPLOYER_POC_ADDRESS2=@EMPLOYER_POC_ADDRESS2,
EMPLOYER_POC_CITY=@EMPLOYER_POC_CITY,
EMPLOYER_POC_STATE=@EMPLOYER_POC_STATE,
EMPLOYER_POC_POSTAL_CODE=@EMPLOYER_POC_POSTAL_CODE,
EMPLOYER_POC_COUNTRY=@EMPLOYER_POC_COUNTRY,
EMPLOYER_POC_PROVINCE=@EMPLOYER_POC_PROVINCE,
EMPLOYER_POC_PHONE=@EMPLOYER_POC_PHONE,
EMPLOYER_POC_PHONE_EXT=@EMPLOYER_POC_PHONE_EXT,
EMPLOYER_POC_EMAIL=@EMPLOYER_POC_EMAIL,
AGENT_REPRESENTING_EMPLOYER=@AGENT_REPRESENTING_EMPLOYER,
AGENT_ATTORNEY_LAST_NAME=@AGENT_ATTORNEY_LAST_NAME,
AGENT_ATTORNEY_FIRST_NAME=@AGENT_ATTORNEY_FIRST_NAME,
AGENT_ATTORNEY_MIDDLE_NAME=@AGENT_ATTORNEY_MIDDLE_NAME,
AGENT_ATTORNEY_ADDRESS1=@AGENT_ATTORNEY_ADDRESS1,
AGENT_ATTORNEY_ADDRESS2=@AGENT_ATTORNEY_ADDRESS2,
AGENT_ATTORNEY_CITY=@AGENT_ATTORNEY_CITY,
AGENT_ATTORNEY_STATE=@AGENT_ATTORNEY_STATE,
AGENT_ATTORNEY_POSTAL_CODE=@AGENT_ATTORNEY_POSTAL_CODE,
AGENT_ATTORNEY_COUNTRY=@AGENT_ATTORNEY_COUNTRY,
AGENT_ATTORNEY_PROVINCE=@AGENT_ATTORNEY_PROVINCE,
AGENT_ATTORNEY_PHONE=@AGENT_ATTORNEY_PHONE,
AGENT_ATTORNEY_PHONE_EXT=@AGENT_ATTORNEY_PHONE_EXT,
AGENT_ATTORNEY_EMAIL_ADDRESS=@AGENT_ATTORNEY_EMAIL_ADDRESS,
LAWFIRM_NAME_BUSINESS_NAME=@LAWFIRM_NAME_BUSINESS_NAME,
STATE_OF_HIGHEST_COURT=@STATE_OF_HIGHEST_COURT,
NAME_OF_HIGHEST_STATE_COURT=@NAME_OF_HIGHEST_STATE_COURT,
WORKSITE_WORKERS=@WORKSITE_WORKERS,
SECONDARY_ENTITY=@SECONDARY_ENTITY,
SECONDARY_ENTITY_BUSINESS_NAME=@SECONDARY_ENTITY_BUSINESS_NAME,
WORKSITE_ADDRESS1=@WORKSITE_ADDRESS1,
WORKSITE_ADDRESS2=@WORKSITE_ADDRESS2,
WORKSITE_CITY=@WORKSITE_CITY,
WORKSITE_COUNTY=@WORKSITE_COUNTY,
WORKSITE_STATE=@WORKSITE_STATE,
WORKSITE_POSTAL_CODE=@WORKSITE_POSTAL_CODE,
WAGE_RATE_OF_PAY_FROM=@WAGE_RATE_OF_PAY_FROM,
WAGE_RATE_OF_PAY_TO=@WAGE_RATE_OF_PAY_TO,
WAGE_UNIT_OF_PAY=@WAGE_UNIT_OF_PAY,
PREVAILING_WAGE=@PREVAILING_WAGE,
PW_UNIT_OF_PAY=@PW_UNIT_OF_PAY,
PW_TRACKING_NUMBER=@PW_TRACKING_NUMBER,
PW_WAGE_LEVEL=@PW_WAGE_LEVEL,
PW_OES_YEAR=@PW_OES_YEAR,
PW_OTHER_SOURCE=@PW_OTHER_SOURCE,
PW_OTHER_YEAR=@PW_OTHER_YEAR,
PW_SURVEY_PUBLISHER=@PW_SURVEY_PUBLISHER,
PW_SURVEY_NAME=@PW_SURVEY_NAME,
TOTAL_WORKSITE_LOCATIONS=@TOTAL_WORKSITE_LOCATIONS,
AGREE_TO_LC_STATEMENT=@AGREE_TO_LC_STATEMENT,
`H-1B_DEPENDENT`=@H1B_DEPENDENT,
WILLFUL_VIOLATOR=@WILLFUL_VIOLATOR,
SUPPORT_H1B=@SUPPORT_H1B,
STATUTORY_BASIS=@STATUTORY_BASIS,
APPENDIX_A_ATTACHED=@APPENDIX_A_ATTACHED,
PUBLIC_DISCLOSURE=@PUBLIC_DISCLOSURE,
PREPARER_LAST_NAME=@PREPARER_LAST_NAME,
PREPARER_FIRST_NAME=@PREPARER_FIRST_NAME,
PREPARER_MIDDLE_INITIAL=@PREPARER_MIDDLE_INITIAL,
PREPARER_BUSINESS_NAME=@PREPARER_BUSINESS_NAME,
PREPARER_EMAIL=@PREPARER_EMAIL;




select * from h1b_data;


select count(*) from h1b_data;


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/LCA_Disclosure_Data_FY2025_Q3.csv'
INTO TABLE h1b_data
CHARACTER SET latin1
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;


select * from h1b_data;

select count(*) from h1b_data;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/LCA_Disclosure_Data_FY2025_Q4.csv'
INTO TABLE h1b_data
CHARACTER SET latin1
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;


use h1b_data;

create table h1b_cleaned_data(
CASE_NUMBER varchar(100),
CASE_STATUS varchar(100),
RECEIVED_DATE  varchar(100),
DECISION_DATE  varchar(100),
VISA_CLASS varchar(100),
JOB_TITLE  varchar(100),
SOC_CODE varchar(100),
SOC_TITLE  varchar(100),
FULL_TIME_POSITION  varchar(100),
TOTAL_WORKER_POSITIONS  varchar(100),
NEW_EMPLOYMENT     varchar(100),
AMENDED_PETITION  varchar(100),
EMPLOYER_NAME      varchar(200),
EMPLOYER_STATE    varchar(100),
NAICS_CODE          varchar(100),
EMPLOYER_POC_JOB_TITLE varchar(100),
WORKSITE_WORKERS  varchar(100),
WORKSITE_CITY      varchar(100),
WORKSITE_COUNTY varchar(100),
WORKSITE_STATE  varchar(100),
WAGE_RATE_OF_PAY_FROM  varchar(100),
WAGE_RATE_OF_PAY_TO   varchar(100),
WAGE_UNIT_OF_PAY   varchar(100),
PREVAILING_WAGE  varchar(100),
PW_UNIT_OF_PAY  varchar(100),
PW_WAGE_LEVEL varchar(100),
`H-1B_DEPENDENT` varchar(100));



LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/h1b_cleaned_data.csv'
INTO TABLE h1b_cleaned_data
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


select * from h1b_cleaned_data;


-- Counting the total number of records in the h1b_cleaned_data table
select count(*) from h1b_cleaned_data;